pool:
  vmImage: 'ubuntu-latest' # Adjust VM image if needed

stages:
- stage: Build
  jobs:
  - job: Build_Job
    steps:
    - task: Maven@3 # Use the appropriate Maven version task
      inputs:
        mavenVersionOption: 'Default' # Use default Maven version provided by the task
        mavenPomFile: 'pom.xml' # Path to your pom.xml file
        goals: 'clean package' # Maven goals to execute (clean and package)
        publishJUnitResults: true # Optionally publish JUnit test results
        javaHomeOption: 'JDKVersion' # Specify the JDK version
        jdkVersionOption: '1.8' # Adjust this based on your project's requirements
        jdkArchitectureOption: 'x64' # Specify the architecture

